name: calculator
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

workspace:
  - packages/app_constants
  - packages/app_database
  - packages/app_localizations
  - packages/app_providers
  - packages/app_router
  - packages/app_utils
  - packages/app_widgets
  - packages/screen_history
  - packages/service_native_splash
  - packages/service_system_chrome

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  infinity_widgets: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - LICENSE
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
