name: app_router
description: Defines the router used in the application.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  screen_splash:
    path: ../../packages/screen_splash

  screen_home:
    path: ../../packages/screen_home

  screen_history:
    path: ../../packages/screen_history

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
