name: screen_splash
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  infinity_widgets: ^1.0.3

  app_constants: ^1.0.0
  app_router: ^1.0.0

  service_native_splash: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
