name: app_widgets
description: Defines the widgets used in the application.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  app_constants: ^1.0.0
  app_providers: ^1.0.0
  app_utils: ^1.0.0

  wolt_modal_sheet: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
