name: Build and Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output-name: linux
          - os: macos-latest
            output-name: macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Get dependencies
        run: flutter pub get

      - name: Build Linux x64
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux --release

      - name: Build Android
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release --split-per-abi

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: flutter build macos --release

      - name: Archive Linux x64 Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd build/linux/x64/release/bundle
          zip -r ../../../../../calculator-linux-x64.zip .

      - name: Archive Android Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk calculator-android-arm64.apk
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk calculator-android-armv7.apk
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk calculator-android-x64.apk
          cp build/app/outputs/flutter-apk/app-x86-release.apk calculator-android-x86.apk

      - name: Archive macOS Build
        if: matrix.os == 'macos-latest'
        run: |
          cd build/macos/Build/Products/Release
          zip -r ../../../../../calculator-macos.zip *.app

      - name: Upload Linux Artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            calculator-linux-x64.zip
            calculator-android-*.apk

      - name: Upload macOS Artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: calculator-macos.zip

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List Files
        run: ls -R artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            artifacts/**/*.zip
            artifacts/**/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

