name: Build and Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output-name: linux
          - os: windows-latest
            output-name: windows
          - os: macos-latest
            output-name: macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Get dependencies
        run: flutter pub get

      - name: Build Linux x64
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux --release

      # - name: Build Linux ARM64
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     flutter config --enable-linux-desktop
      #     CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ flutter build linux --release --target-platform linux-arm64

      - name: Build Android
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: flutter build macos --release

      - name: Archive Linux x64 Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd build/linux/x64/release/bundle
          zip -r ../../../../../calculator-linux-x64.zip .

      # - name: Archive Linux ARM64 Build
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     cd build/linux/arm64/release/bundle
      #     zip -r ../../../../../calculator-linux-arm64.zip .

      - name: Archive Android Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk calculator-android.apk

      - name: Archive Windows Build
        if: matrix.os == 'windows-latest'
        run: |
          cd build/windows/x64/runner/Release
          7z a ../../../../../calculator-windows.zip .

      - name: Archive macOS Build
        if: matrix.os == 'macos-latest'
        run: |
          cd build/macos/Build/Products/Release
          zip -r ../../../../../calculator-macos.zip *.app

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            calculator-*.zip
            calculator-android.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
